version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.1.1}
    networks:
    - cherry-network
    command: start --certs-dir=/cockroach/certs
    volumes:
    - ~/volumes/cherry/configs/roach:/cockroach/certs
    ports:
    - 8181:8080
    - 26257:26257

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.1.1}
    networks:
    - cherry-network
    command: start --certs-dir=/cockroach/certs --join=roach-0
    volumes:
    - ~/volumes/cherry/configs/roach:/cockroach/certs

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.1.1}
    networks:
    - cherry-network
    command: start --certs-dir=/cockroach/certs --join=roach-0
    volumes:
    - ~/volumes/cherry/configs/roach:/cockroach/certs

  db-init:
    container_name: db-init
    hostname: db-init
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.1.1}
    networks:
    - cherry-network
    volumes:
    - ~/volumes/cherry/configs/roach:/cockroach/certs
    entrypoint: "/bin/bash"
    command: /cockroach/certs/setup_db.sh