version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper-0
    networks:
      - cherry-network
    image: wurstmeister/zookeeper
    hostname: zookeeper-0
    ports:
    - "2181:2181"

  kafka-0:
    container_name: kafka-0
    networks:
      - cherry-network
    image: wurstmeister/kafka
    hostname: kafka-0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/volumes/cherry/data/kafka/kafka-0:/kafka
    ports:
    - "9092:9092"

  kafka-1:
    container_name: kafka-1
    networks:
      - cherry-network
    image: wurstmeister/kafka
    hostname: kafka-1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/volumes/cherry/data/kafka/kafka-1:/kafka
    ports:
    - "9093:9092"

  kafka-2:
    container_name: kafka-2
    networks:
      - cherry-network
    image: wurstmeister/kafka
    hostname: kafka-2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181
      KAFKA_BROKER_ID: 2
      KAFKA_NUM_PARTITIONS: 3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/volumes/cherry/data/kafka/kafka-2:/kafka
    ports:
    - "9094:9092"
