version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:
  zk-0:
    container_name: zk-0
    hostname: zk-0
    networks:
      - cherry-network
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka-0:
    container_name: kafka-0
    hostname: kafka-0
    networks:
      - cherry-network
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk-0:2181
      KAFKA_CREATE_TOPICS: "topic-cherry:1:1"
    ports:
      - 9092:9092
