version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:

  nats-0:
    container_name: nats-0
    hostname: nats-0
    image: nats-streaming:0.11.2-linux
    networks:
    - cherry-network
    command: -p 4222 -m 8222 -cid cherry_ft -store file -dir /datastore -user leenux -pass Synjones123 -ft_group "ft" -cluster nats://nats-0:6222 -routes nats://nats-1:6223
    volumes:
    - ~/volumes/cherry/data/nats/nats-0:/datastore
    ports:
    - 4222:4222
    - 8222:8222

  nats-1:
    container_name: nats-1
    hostname: nats-1
    image: nats-streaming:0.11.2-linux
    networks:
    - cherry-network
    command: -p 4223 -m 8223 -cid cherry_ft -store file -dir /datastore -user leenux -pass Synjones123 -ft_group "ft" -cluster nats://nats-1:6223 -routes nats://nats-0:6222
    volumes:
    - ~/volumes/cherry/data/nats/nats-1:/datastore
    ports:
    - 4223:4223
    - 8223:8223

