FROM redis:5.0.3-alpine

ENV SENTINEL_CONF_PATH=/etc/redis/sentinel.conf \
    SENTINEL_PORT=26379 \
    SENTINEL_MASTER_NAME=redis-master \
    SENTINEL_REDIS_IP=127.0.0.1 \
    SENTINEL_REDIS_PORT=6379 \
    SENTINEL_REDIS_PWD=Synjones123 \
    SENTINEL_QUORUM=2 \
    SENTINEL_DOWN_AFTER=5000 \
    SENTINEL_PARALLEL_SYNCS=1 \
    SENTINEL_FAILOVER_TIMEOUT=5000

RUN apk add --no-cache gettext

ADD sentinel.conf.sample /etc/redis/sentinel.conf.sample

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 26379
CMD ["redis-server"]
